package hcmus.android.gallery1.helpers

enum class ScreenConstant {
    COLLECTION_LIST_ALBUM,
    COLLECTION_LIST_DATE,
    COLLECTION_VIEW,
    COLLECTION_VIEW_CUSTOM_ALBUM,
    DIALOG_ADD_PHOTO_INTO_ALBUMS,
    DIALOG_ADD_PHOTOS_INTO_ALBUM,
    DIALOG_CHANGE_THEME,
    DIALOG_NEW_ALBUM,
    DIALOG_RENAME,
    EDIT,
    IMAGE_LIST_ALL,
    IMAGE_LIST_FAVOURITE,
    IMAGE_VIEW,
    IMAGE_VIEW_FROM_CUSTOM_ALBUM,
    IMAGE_VIEW_NO_PAGER,
    MAIN,
    SECRET_PASSCODE
}